/**
 * Concrete implementation of IServiceRepository backed by DBClient.
 *
 * All queries are scoped by client_id — no RLS on Aurora, so per-query
 * scoping is mandatory (matching project security conventions).
 */
import type { IDBClient } from '@/lib/db/IDBClient'
import type { Database, ServiceDefinitionRow } from '@/lib/db/schema'
import type { IServiceRepository } from './IServiceRepository'

export class ServiceRepository implements IServiceRepository {
  constructor(private readonly db: IDBClient<Database>) {}

  async listDefaults(category?: string): Promise<ServiceDefinitionRow[]> {
    let query = this.db.kysely
      .selectFrom('service_definitions')
      .selectAll()
      .where('client_id', 'is', null)
      .orderBy('created_at', 'asc')

    if (category) {
      query = query.where('category', '=', category)
    }

    const rows = await query.execute()
    return rows as ServiceDefinitionRow[]
  }

  async listCustomForClient(
    clientId: string,
    category?: string,
  ): Promise<ServiceDefinitionRow[]> {
    let query = this.db.kysely
      .selectFrom('service_definitions')
      .selectAll()
      .where('client_id', '=', clientId)
      .orderBy('created_at', 'asc')

    if (category) {
      query = query.where('category', '=', category)
    }

    const rows = await query.execute()
    return rows as ServiceDefinitionRow[]
  }

  async createCustomDefinition(
    clientId: string,
    data: { icon: string; label: string; category: string },
  ): Promise<ServiceDefinitionRow> {
    const row = await this.db.kysely
      .insertInto('service_definitions')
      // id/created_at/updated_at are generated by the DB (DEFAULT gen_random_uuid() / now())
      .values({
        client_id: clientId,
        category: data.category,
        icon: data.icon,
        name_key: null,
        custom_label: data.label.trim(),
      } as unknown as Parameters<ReturnType<typeof this.db.kysely.insertInto<'service_definitions'>>['values']>[0])
      .returningAll()
      .executeTakeFirstOrThrow()

    return row as ServiceDefinitionRow
  }

  async listSelectedForClient(
    clientId: string,
    category?: string,
  ): Promise<ServiceDefinitionRow[]> {
    let query = this.db.kysely
      .selectFrom('client_services')
      .innerJoin(
        'service_definitions',
        'service_definitions.id',
        'client_services.service_definition_id',
      )
      .selectAll('service_definitions')
      .where('client_services.client_id', '=', clientId)
      .orderBy('service_definitions.created_at', 'asc')

    if (category) {
      query = query.where('service_definitions.category', '=', category)
    }

    const rows = await query.execute()
    return rows as ServiceDefinitionRow[]
  }

  async setSelections(
    clientId: string,
    category: string,
    definitionIds: string[],
  ): Promise<void> {
    // Use the raw pg client from the pool for a transaction so we can do
    // delete-then-insert atomically.
    await this.db.kysely.transaction().execute(async (trx) => {
      // Delete existing selections for this client + category
      await trx
        .deleteFrom('client_services')
        .where('client_id', '=', clientId)
        .where((eb) =>
          eb.exists(
            eb
              .selectFrom('service_definitions')
              .select('service_definitions.id')
              .where('service_definitions.id', '=', eb.ref('client_services.service_definition_id'))
              .where('service_definitions.category', '=', category),
          ),
        )
        .execute()

      if (definitionIds.length === 0) return

      // Insert new selections (id/created_at generated by DB DEFAULT)
      await trx
        .insertInto('client_services')
        .values(
          definitionIds.map((defId) => ({
            client_id: clientId,
            service_definition_id: defId,
          })) as unknown as Parameters<ReturnType<typeof trx.insertInto<'client_services'>>['values']>[0],
        )
        .execute()
    })
  }

  async deleteCustomDefinition(clientId: string, definitionId: string): Promise<void> {
    await this.db.kysely
      .deleteFrom('service_definitions')
      .where('id', '=', definitionId)
      .where('client_id', '=', clientId) // ensures ownership; cannot delete defaults (client_id IS NULL)
      .execute()
  }
}
